emby api支持镶套文件夹
allanpk716/ChineseSubFinder pull request #84
Opened 2021-10-20 21:44 UTC by wloot

2021-10-21 02:57 UTC, allanpk716 commented
> 加入像radarr那样的路径转换配置的话，应该只需要在匹配前把emby给出的目录全局替换一次就可以了，后面按实际csf程序能访问的来似乎不需要改动。

嗯，你的代码晚点再合并，然后需要兼容之前没有路径转换配置的就好了。体力活，问题不大。

2021-11-05 03:43 UTC, allanpk716 commented
我刚测试了下我自己的使用环境，多层文件夹应该可以正确转换了。但是，还是有些需要注意的，我先贴图，然后我尝试描述一下，有点绕。

先看截图 1、2

## 截图 1
![image](https://user-images.githubusercontent.com/1176000/140454301-f30782b0-31e0-4cd8-832b-dfefad9b0dfa.png)

## 截图 2
![image](https://user-images.githubusercontent.com/1176000/140454313-5b2e49c2-732f-4288-b6b1-002a8dc2b3ce.png)

之前的思路和现在的思路都是，找到“电影”这个所有电影的根目录，然后去转换 emby 的地址和 实际地址（或者本程序 docker 中地址）的转换。

之前的代码有bug，导致这一步转换的时候，可能取到的索引是错误的。见截图 1、2、3，就可以看出问题所在。进过分析，我改进了这里的逻辑。见，截图3.

## 截图 3
![image](https://user-images.githubusercontent.com/1176000/140454534-28a4e7a1-4f80-482e-9484-05af6004a333.png)


这样就应该可以正确去比较他们的“Ancestors”了，因为是逆序的，也就是 emby 的“根”向上一级。还是见截图 1、2。

那么改进后，就算嵌套也是去查找 emby 的“根”向上一级的“电影”真实的目录名称，应该就能够正确的匹配上。

你试试你的情况下是否能够正确转换了。我不太懂怎么发送 github 上的提交记录到这里进行回复。所以我把我提交信息发上来，你手动去找一下吧。在 dev 分支。:joy:

```
Revision: 619b8a59a0ec2a0b3c44751b46e0cf8f67ef22f0
Author: allan716 <525223688@qq.com>
Date: 2021/11/5 11:22:52
Message:
修复，emby 内置路径与本程序读取到的 movie 和 series 路径的映射逻辑；

Signed-off-by: allan716 <525223688@qq.com>
```

2021-11-05 07:50 UTC, allanpk716 commented
不过就算改到这个版本，也是不支持“连续剧”的嵌套的，理论上按“电影”的思路也可以改，但是还是规范点吧···后续整Web界面后，想怎么设置映射关系多个目录支持都好办。

2021-11-26 23:29 UTC, wloot commented
试了下最新版本, 电影确实可以支持多层文件夹了. 但是影集还是不行.

2021-11-29 00:31 UTC, allanpk716 requested changes
这样的改动可能会有时候无法触发后续的逻辑了。

2021-12-30 10:11 UTC, wloot commented
请问新版本能考虑也修复 series 的目录映射逻辑吗? 目前 https://github.com/allanpk716/ChineseSubFinder/commit/f6906c607f696346b28f1fef54416721a72ca361 好像只修复了电影的.

2021-12-30 10:18 UTC, allanpk716 commented
> 请问新版本能考虑也修复 series 的目录映射逻辑吗? 目前 [f6906c6](https://github.com/allanpk716/ChineseSubFinder/commit/f6906c607f696346b28f1fef54416721a72ca361) 好像只修复了电影的.

我拉了个朋友帮我整 Web 设置页面，多个目录嵌套的问题会提供设置的界面。页面设计（初步待定的功能）见，https://github.com/allanpk716/ChineseSubFinder/tree/docs/DesignFile/Web%E7%95%8C%E9%9D%A2%E8%AE%BE%E8%AE%A1

需要使用 https://excalidraw.com/ 这个网站来打开使用。如果还有其他的想法，不是很复杂的话，可以单独针对这个 Web 设置页面提需求。

2022-02-06 08:29 UTC, closed without merging